# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='PerformanceFeatures',
            new_name='PerformanceFeature',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
