# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170913_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureIncompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='UserDetails',
        ),
        migrations.RemoveField(
            model_name='performancefeature',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='performancefeature',
            name='performance_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
        migrations.AddField(
            model_name='feature',
            name='performance_id',
            field=models.ManyToManyField(to='core.Performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 17), verbose_name='date of performance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='time of performance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance_id',
            field=models.ManyToManyField(to='core.Performance'),
        ),
        migrations.DeleteModel(
            name='PerformanceFeature',
        ),
        migrations.AddField(
            model_name='featureincompatibility',
            name='feature_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Feature'),
        ),
        migrations.AddField(
            model_name='featureincompatibility',
            name='user_feature_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserFeature'),
        ),
    ]
