# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170917_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='performance_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.Performance'),
            preserve_default=False,
        ),
    ]
