# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170918_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='id',
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Performance'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
