# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170919_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
