# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170919_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('property', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userfeature',
            name='id',
        ),
        migrations.AddField(
            model_name='userfeature',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='feature_name',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
